### Register User
POST http://localhost:9080/register
Content-Type: application/json

{
  "username": "sniki12",
  "password": "1234",
  "email": "sniki@gmail.com",
  "name": "Sniki"
}

###

### Login User
POST http://localhost:9080/login
Content-Type: application/json

{
  "email": "sniki@gmail.com",
  "password": "1234"
}

###

### User and Profile
GET http://localhost:9080/get_user_and_profile?token=cdee03caf27cabd9d13b95f8187fc79b6ce61be008504c21848cbb0b55c41c2f

###
POST http://localhost:9080/update_profile_data
Content-Type: application/json

{
  "token": "cdee03caf27cabd9d13b95f8187fc79b6ce61be008504c21848cbb0b55c41c2f",
  "bio": "Hey, I am Sniki. I am from Mumbai and work at Google company. I am a true learner with Experience.",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Google",
      "position": "CTO",
      "years": "1+"
    }
  ],
  "education": [
    {
      "school": "IIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2020-2024"
    }
  ]
}


### Update Profile
POST http://localhost:9080/update_profile_data
Content-Type: application/json

{
  "token": "22db76fec58aa4334dbb50702b58c4dfc07de0d8989a2da7aaffe95b284ebd6a",
  "bio": "Hey, I am Pandu. I am from Hyderabad and work at XYZ company. I am a true learner.",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2020-2024"
    }
  ]
}



###

### Get All Users
GET http://localhost:9080/user/get_all_users


### Create Post
POST http://localhost:9080/post
Content-Type: application/json

{
  "token": "22db76fec58aa4334dbb50702b58c4dfc07de0d8989a2da7aaffe95b284ebd6a",
  "body": "Hello this is my first LinkedIn clone post!"
}

###      
GET http://localhost:9080/posts

